server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    access_log /var/log/inout/access.log;
    access_log /dev/stdout;
    error_log /var/log/inout/error.log warn;
    error_log /dev/stderr warn;

    location / { try_files $uri $uri/ /index.html; }
}
